### ISSUE TITLE
Adding rules to contributors

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/noblog-api#3]
**Summary**
Create `.github/CONTRIBUTING.md` file with information on how to give a pull request or create an issue in the project and some rules for new contributors.

**More information about file**
The file will be located on the main page of the project.
Because the file does not exist, you can suggest a new format for it.
The file should contain information about how to start a contribution in the project, how to create an issue, and how to propose a change.

Do not forget to add your name to the list of contributors, located in `.github/CONTRIBUTORS.md` :heavy_check_mark: 
Happy Hacktoberfest! :smile: 
Any questions, just talk :wink:
Let's start? :+1: :rocket:

**Comment by Corinnehuilin** [comment]
Hey, I'd like to take this issue on. If I have any questions I'll let you know.

**Comment by gustafsilva** [comment]
It would be great @Corinnehuilin :+1: 
I am available if you have any questions! :smile:
