### ISSUE TITLE
Create entity and relationship diagram for database

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/noblog-api#5]
**Summary**
Create an entity and relationship diagram for the database schema.

**More information about file**
Add the generated image from the entity and relationship diagram in the `docs/img/`folder.
To assist in creating the diagram, you can view the _data dictionary_ [here](https://github.com/gustafsilva/noblog-api/blob/master/docs/database/DATA_DICTIONARY.md) :book: 

Do not forget to add your name to the list of contributors, located in `.github/CONTRIBUTORS.md` :heavy_check_mark:
Happy Hacktoberfest! :smile:
Any questions, just talk :wink:
Let's start? :+1: :rocket:

**Comment by nigeldelviero** [comment]
I can work on this one.

**Comment by gustafsilva** [comment]
It would be great @nigeldelviero :+1: 
I am here for any questions :smile:
